/* =====================================================================
   stage.js — three-axis stepper motion straight from the Pi's GPIO.

   No Arduino, no STM32. The objection to driving steppers from Linux is
   that the scheduler will preempt a bit-banged pulse train and drop steps.
   That objection is real and this code does not bit-bang: pigpio builds a
   waveform and clocks it out over DMA, so the pulse timing is generated by
   the hardware and is unaffected by anything the CPU is doing. A dedicated
   MCU earns its place when you add encoders, limit switches or coordinated
   motion during exposure. For "move, stop, take a picture", it does not.

   Falls back to a simulator when pigpio is absent, so the service and the
   scan logic can be developed and tested on a laptop.
   ===================================================================== */
'use strict';

const DEFAULT_PINS = { X: { step: 17, dir: 27 }, Y: { step: 22, dir: 23 },
                       Z: { step: 24, dir: 25 }, EN: 4 };

const sleep = ms => new Promise(r => setTimeout(r, ms));

class SimStage {
  constructor(opts = {}) {
    this.kind = 'simulator';
    this.pos = { X: 0, Y: 0, Z: 0 };
    this.umPerStep = opts.umPerStep || { X: 5, Y: 5, Z: 1 };
  }
  async move(axis, steps) {
    await sleep(Math.min(400, 2 + Math.abs(steps) * 0.05));
    this.pos[axis] += steps;
    return this.pos[axis];
  }
  async moveUm(axis, um) { return this.move(axis, Math.round(um / this.umPerStep[axis])); }
  posUm(axis) { return this.pos[axis] * this.umPerStep[axis]; }
  zero() { this.pos = { X: 0, Y: 0, Z: 0 }; }
  release() {}
  dispose() {}
}

class PiStage {
  constructor(opts = {}) {
    this.kind = 'pigpio';
    this.pins = opts.pins || DEFAULT_PINS;
    this.umPerStep = opts.umPerStep || { X: 5, Y: 5, Z: 1 };
    this.minDelayUs = opts.minDelayUs || 400;    // fastest half-pulse
    this.startDelayUs = opts.startDelayUs || 1600; // slowest, for the ramp
    this.rampSteps = opts.rampSteps || 60;
    this.invert = opts.invert || {};             // e.g. { Y: true } if an axis runs backwards
    this.pos = { X: 0, Y: 0, Z: 0 };

    this.pigpio = require('pigpio');             // throws if unavailable -> caller falls back
    const { Gpio } = this.pigpio;
    this.gpio = {};
    for (const ax of ['X', 'Y', 'Z']) {
      this.gpio[ax] = {
        step: new Gpio(this.pins[ax].step, { mode: Gpio.OUTPUT }),
        dir : new Gpio(this.pins[ax].dir,  { mode: Gpio.OUTPUT }),
      };
      this.gpio[ax].step.digitalWrite(0);
    }
    this.en = new Gpio(this.pins.EN, { mode: Gpio.OUTPUT });
    this.en.digitalWrite(1);                     // drivers disabled (active low)
  }

  /* Linear ramp: a stepper asked to start at full speed simply stalls, and a
     stalled stepper loses position silently — the stage ends up somewhere the
     software does not know about, and every field after it is wrong. */
  _delayFor(i, n) {
    const ramp = Math.min(this.rampSteps, Math.floor(n / 2));
    if (ramp <= 0) return this.minDelayUs;
    const into = Math.min(i, n - 1 - i, ramp);
    const t = into / ramp;
    return Math.round(this.startDelayUs + (this.minDelayUs - this.startDelayUs) * t);
  }

  async move(axis, steps) {
    if (!steps) return this.pos[axis];
    const g = this.gpio[axis];
    let fwd = steps > 0;
    if (this.invert[axis]) fwd = !fwd;
    g.dir.digitalWrite(fwd ? 1 : 0);
    this.en.digitalWrite(0);                     // enable drivers
    await sleep(2);                              // let DIR settle before the first edge

    const n = Math.abs(steps), mask = 1 << this.pins[axis].step;
    const CHUNK = 3000;                          // pigpio waveforms are finite
    for (let base = 0; base < n; base += CHUNK) {
      const cnt = Math.min(CHUNK, n - base);
      const pulses = [];
      for (let i = 0; i < cnt; i++) {
        const d = this._delayFor(base + i, n);
        pulses.push({ gpioOn: mask, gpioOff: 0, usDelay: d });
        pulses.push({ gpioOn: 0, gpioOff: mask, usDelay: d });
      }
      this.pigpio.waveClear();
      this.pigpio.waveAddGeneric(pulses);
      const id = this.pigpio.waveCreate();
      this.pigpio.waveTxSend(id, this.pigpio.WAVE_MODE_ONE_SHOT);
      while (this.pigpio.waveTxBusy()) await sleep(4);
      this.pigpio.waveDelete(id);
    }
    this.pos[axis] += steps;
    this.en.digitalWrite(1);                     // release: motors run cool, stage holds by friction
    return this.pos[axis];
  }

  async moveUm(axis, um) { return this.move(axis, Math.round(um / this.umPerStep[axis])); }
  posUm(axis) { return this.pos[axis] * this.umPerStep[axis]; }
  zero() { this.pos = { X: 0, Y: 0, Z: 0 }; }
  release() { this.en.digitalWrite(1); }
  dispose() { try { this.release(); this.pigpio.terminate(); } catch {} }
}

function createStage(opts = {}) {
  if (opts.sim) return new SimStage(opts);
  try {
    return new PiStage(opts);
  } catch (e) {
    console.warn('[stage] pigpio unavailable (' + e.message + ') — running simulated');
    return new SimStage(opts);
  }
}

module.exports = { createStage, SimStage, PiStage, DEFAULT_PINS };
